### ISSUE TITLE
Building In Adventure Gamemode

### ISSUE THREAD

**Issue by XKazzuKX** [CloudburstMC/Server#24]
### Expected Behavior

Not being able to build in Adventure Gamemode

### Actual Behavior

You could build in Adventure Gamemode which was server side effected

### Steps to Reproduce

https://youtu.be/ZVufEhLd_t0

### Debug information

* Debug link: https://hastebin.com/uyutadevog
* Timings link (if relevant): N/A

### Crashdump, Backtrace or Other Files

**Checklist**:

- [X] I included a `/debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of Nukkit
- [X] I Made sure the bug/error is not caused by a plugin

**Comment by hungerfan55** [comment]
This is fixes btw
