### ISSUE TITLE
Japanese language garbling

### ISSUE THREAD

**Issue by LavieGS** [CloudburstMC/Server#33]
### Expected Behavior
Like Cloudburst Nukkit (1.0), console should display Japanese successfully.

### Actual Behavior
Console returns a list of garbled, meaningless characters.

### Steps to Reproduce
Set your Cloudburst Server (2.0) language to ja_JP, you can easily check.

### Debug information
* Debug link:https://hastebin.com/bezipuximo
* Timings link (if relevant):

### Crashdump, Backtrace or Other Files

**Checklist**:
- [X] I included a `/debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of Nukkit
- [X] I Made sure the bug/error is not caused by a plugin

![image](https://user-images.githubusercontent.com/46153563/89641455-a9bf7600-d8ec-11ea-82f9-b9f47a886e46.png)

**Comment by tuilakhanh** [comment]
Try start server with utf8 flag

java -Dfile.encoding=UTF8 -jar nukkit.jar

**Comment by LavieGS** [comment]
in 1.0, it wasn't garbled even by default so i had no idea
Solved Completely. Thanks!
