### ISSUE TITLE
A list of all blocks that do not work properly in CloudBurst server

### ISSUE THREAD

**Issue by LucGamesYT** [CloudburstMC/Server#36]
**Blocks that don't work Page 1**

**Wood Planks:**
- [x] Spruce Wood Planks -> Oak Wood Planks
- [x] Birch Wood Planks -> Oak Wood Planks
- [x] Jungle Wood Planks -> Oak Wood Planks
- [x] Acacia Wood Planks -> Oak Wood Planks
- [x] Dark Oak Wood Planks -> Oak Wood Planks

**Walls**
- [x] Mossy Cobblestone Wall -> Cobblestone Wall
- [x] Granite Wall -> Cobblestone Wall & They do not connect
- [x] Diorite Wall -> Cobblestone Wall & They do not connect
- [x] Andesite Wall -> Cobblestone Wall & They do not connect
- [x] Sandstone Wall -> Cobblestone Wall & They do not connect
- [x] Red Sandstone Wall -> Cobblestone Wall & They do not connect
- [x] Stone Brick Wall -> Cobblestone Wall & They do not connect
- [x] Mossy Stone Brick Wall -> Cobblestone Wall & They do not connect
- [x] Brick Wall -> Cobblestone Wall & They do not connect
- [x] Nether Brick Wall -> Cobblestone Wall & They do not connect
- [x] Red Nether Brick Wall -> Cobblestone Wall & They do not connect
- [x] End Stone Brick Wall -> Cobblestone Wall & They do not connect
- [x] Prismarine Wall -> Cobblestone Wall & They do not connect

**Fence**
- [x] Spruce Fence -> Oak Fence
- [x] Birch Fence -> Oak Fence
- [x] Jungle Fence -> Oak Fence
- [x] Acacia Fence -> Oak Fence
- [x] Dark Oak Fence -> Oak Fence

**Stairs**
- [x] Crimson Stairs -> Wrong Direction & They connect wrong
- [x] Warped Stairs -> Wrong Direction & They connect wrong
- [x] Blackstone Stairs -> Wrong Direction & They connect wrong
- [x] Polished Black Stone Brick Stairs -> Wrong Direction & They connect wrong

**Doors**
- [x] Crimson Door -> Can not be placed
- [x] Warped Door -> Can not be placed

**Colored Glass**
- [x] Light Grey Stained Glass -> White Stained Glas
- [x] Grey Stained Glass -> White Stained Glas
- [x] Black Stained Glass -> White Stained Glas
- [x] Brown Stained Glass -> White Stained Glas
- [x] Red Stained Glass -> White Stained Glas
- [x] Orange Stained Glass -> White Stained Glas
- [x] Yellow Stained Glass -> White Stained Glas
- [x] Lime Stained Glass -> White Stained Glas
- [x] Green Stained Glass -> White Stained Glas
- [x] Cyan Stained Glass -> White Stained Glas
- [x] Light Blue Stained Glass -> White Stained Glas
- [x] Blue Stained Glass -> White Stained Glas
- [x] Purple Stained Glass -> White Stained Glas
- [x] Magenta Stained Glass -> White Stained Glas
- [x] Pink Stained Glass -> White Stained Glas

**Colored Glass Pane**
- [x] Light Grey Stained Glass Pane -> White Stained Glas Pane
- [x] Grey Stained Glass Pane -> White Stained Glas Pane
- [x] Black Stained Glass Pane -> White Stained Glas Pane
- [x] Brown Stained Glass Pane -> White Stained Glas Pane
- [x] Red Stained Glass Pane -> White Stained Glas Pane
- [x] Orange Stained Glass Pane -> White Stained Glas Pane
- [x] Yellow Stained Glass Pane -> White Stained Glas Pane
- [x] Lime Stained Glass Pane -> White Stained Glas Pane
- [x] Green Stained Glass Pane -> White Stained Glas Pane
- [x] Cyan Stained Glass Pane -> White Stained Glas Pane
- [x] Light Blue Stained Glass Pane -> White Stained Glas Pane
- [x] Blue Stained Glass Pane -> White Stained Glas Pane
- [x] Purple Stained Glass Pane -> White Stained Glas Pane
- [x] Magenta Stained Glass Pane -> White Stained Glas Pane
- [x] Pink Stained Glass Pane -> White Stained Glas Pane

**Ladder**
- [x] Cannot be placed and the ladder is dropped immediately

**Trapdoors**
- [x] All trapdoors have a wrong direction

**Slabs**
*If you place the blow on blocks, the board will remain correct, but there is no placement noise and no breakage and a few can only be placed in the lower half of the block.*

- [x] Stone Slab -> Not implemented
- [x] Cobblestone Slab-> Smooth Stone Slab
- [x] Mossy Stone Slab-> Not implemented
- [x] Spruce Wood Slab-> Oak Wood Slab
- [x] Birch Wood Slab-> Oak Wood Slab
- [x] Jungle Wood Slab-> Oak Wood Slab
- [x] Acacia Wood Slab-> Oak Wood Slab
- [x] Dark Oak Wood Slab-> Oak Wood Slab
- [x] Stone Bricks Slab-> Smooth Stone Slab
- [x] Mossy Stone Brick Slab-> Not implemented
- [x] Sandstone Slab-> Smooth Stone Slab
- [x] Cut Sandsatone Slab -> Not implemented
- [x] Smooth Sandstone Slab -> Not implemented
- [x] Red Sandstone Slab -> Not implemented
- [x] Cut Red Sandstone Slab -> Not implemented
- [x] Smooth Red Sandstone Slab -> Not implemented
- [x] Granite Slab -> Not implemented
- [x] Polished Slab -> Not implemented
- [x] Diorite Slab -> Not implemented
- [x] Polished Diorite Slab -> Not implemented
- [x] Andersite Slab -> Not implemented
- [x] Polished Andesite Slab -> Not implemented
- [x] Bricks Slab -> Smooth Stone Slab
- [x] Nether Brick Slab -> Smooth Stone Slab
- [x] Red Nether Brick Slab -> Not implemented
- [x] End Stone Slab -> Not implemented
- [x] Quarz Slab -> Smooth Stone Slab
- [x] Smooth Quarz Slab -> Not implemented
- [x] Prupur Slab -> Not implemented
- [x] Prismarine Slab -> Not implemented
- [x] Dark Prismarine Slab -> Not implemented
- [x] Prismarine Bricks Slab ->  Not implemented

**Bricks**
- [x] Mossy Stone Brick -> Stone Brick
- [x] Cracked Stone Brick -> Stone Brick
- [x] Chiseled Stone Brick -> Stone Brick
- [x] Prismarine Brick -> Prismarine

**Sandstone**
- [x] Chiseled Stonestone ->Sandstone
- [x] Cut Sandstone -> Sandstone
- [x] Smooth Sandstone -> Sandstone

**Quartz**
- [x] Pillar Quartz Block -> Quartz Block
- [x] Chiseled Quartz Block -> Quartz Block
- [x] Smooth Quartz Block -> Quartz Block

**Wool**
- [x] Light Grey Wool -> White Wool
- [x] Gray Wool -> White Wool
- [x] Black Wool -> White Wool
- [x] Brown Wool -> White Wool
- [x] Red Wool -> White Wool
- [x] Orange Wool -> White Wool
- [x] Yellow Wool -> White Wool
- [x] Lime Wool -> White Wool
- [x] Green Wool -> White Wool 
- [x] Cyan Wool -> White Wool
- [x] Light Blue Wool -> White Wool 
- [x] Blue Wool -> White Wool
- [x] Purple Wool -> White Wool
- [x] Magenta Wool -> White Wool
- [x] Pink Wool -> White Wool 

**Wool Carpet**
- [x] Light Grey Wool Carpet-> White Wool Carpet 
- [x] Gray Wool Carpet -> White Wool  Carpet 
- [x] Black Wool Carpet -> White Wool  Carpet 
- [x] Brown Wool Carpet -> White Wool Carpet 
- [x] Red Wool Carpet -> White Wool Carpet 
- [x] Orange Wool Carpet -> White Wool Carpet 
- [x] Yellow Wool Carpet -> White Wool Carpet 
- [x] Lime Wool Carpet -> White Wool Carpet 
- [x] Green Wool Carpet -> White Wool  Carpet 
- [x] Cyan Wool Carpet -> White Wool Carpet 
- [x] Light Blue Wool Carpet -> White Wool  Carpet 
- [x] Blue Wool Carpet -> White Wool Carpet 
- [x] Purple Wool Carpet -> White Wool Carpet 
- [x] Magenta Wool Carpet -> White Wool Carpet 
- [x] Pink Wool Carpet -> White Wool  Carpet 

**Concrete Powder**
- [x] Light Grey Concrete-> White Concrete
- [x] Gray Concrete -> White Concrete
- [x] Black Concrete -> White Concrete
- [x] Brown Concrete -> White Concrete
- [x] Red Concrete -> White Concrete
- [x] Orange Concrete -> White Concrete
- [x] Yellow Concrete -> White Concrete
- [x] Lime Concrete -> White Concrete
- [x] Green Concrete -> White Concrete
- [x] Cyan Concrete -> White Concrete
- [x] Light Blue Concrete -> White Concrete
- [x] Blue Concrete -> White Concrete
- [x] Purple Concrete -> White Concrete
- [x] Magenta Concrete -> White Concrete
- [x] Pink Concrete -> White Concrete

**Terracotter**
- [x] Light Grey Terracotter-> White Terracotter
- [x] Gray Terracotter-> White Terracotter
- [x] Black Terracotter -> White Terracotter
- [x] Brown Terracotter-> White Terracotter
- [x] Red Terracotter-> White Terracotter
- [x] Orange Terracotter-> White Terracotter
- [x] Yellow Terracotter-> White Terracotter
- [x] Lime Terracotter-> White Terracotter
- [x] Green Terracotter-> White Terracotter
- [x] Cyan Terracotter-> White Terracotter
- [x] Light Blue Terracotter-> White Terracotter
- [x] Blue Terracotter-> White Terracotter
- [x] Purple Terracotter-> White Terracotter
- [x] Magenta Terracotter-> White Terracotter
- [x] Pink Terracotter-> White Terracotter

**Blocks that don't work Page 2**

**Axe**
*No sounds and the durability is not deducted*

- Wooden Axe -> Does not work
- Stone Axe -> Does not work
- Iron Axe -> Does not work
- Golden Axe -> Does not work
- Diamond Axe -> Does not work
- Netherite Axe -> Does not work

**Pickaxe**
*No sounds and the durability is not deducted*

- Wooden Pickaxe-> Does not work
- Stone Pickaxe-> Does not work
- Iron Pickaxe-> Does not work
- Golden Pickaxe-> Does not work
- Diamond Pickaxe-> Does not work
- Netherite Pickaxe-> Does not work

**Shovel**
*No sounds and the durability is not deducted*

- Wooden Shovel-> Does not work properly
- Stone Shovel-> Does not work properly
- Iron Shovel-> Does not work properly
- Golden Shovel-> Does not work properly
- Diamond Shovel-> Does not work properly
- Netherite Shovel-> Does not work

**Hoe**
*No sounds and the durability is not deducted*

- Wooden Hoe-> No Sound
- Stone Hoe-> No Sound
- Iron Hoe-> No Sound
- Golden Hoe-> No Sound
- Diamond Hoe-> No Sound
- Netherite Hoe-> Does not work & No Sound

**Arrows**
- All arrows with potion effects does not work

**Shield**
- You can't block

**Fishing Rod**
- The pecking falls further and further down into nothing

**Snowball**
- The snowball keeps falling down into nothing

**Flint and steel**
- Does not work

**Maps**
- All maps does not work

**Crossbow**
- Does not work

**Trident**
- Does not work

**Totem**
- Does not work

**Bottle of enchantment**
- Does not work and flies through the floor

**Splash Potions**
- Does not work

**Blocks that don't work Page 3**

**Torch**
- Soul Torch -> Cannot be placed on walls

**Sea Pickle**
-> Does not work

**Lantern**
- Lantern -> Cannot be placed on walls
- Soul Lantern -> Cannot be placed on walls

**Cartography**
- Does not work

**Flechting Table**
- Does not work

**Smithing Table**
- Does not work

**Beehive**
- Wrong directions

**Furnace**
- Furnace -> Wrong directions
- Blast Furnace -> Wrong directions  & does not worke
- Smoker -> wrong directions & does not work

**Campfire**
- Campfire -> Does not work
- Soul Campfire -> Does not work and can not be placed

**Brewing Stand**
- Does not work

**Anvils**
- Anvil -> Wrong directions & does not work
- Slightly Damaged Anvil -> Wrong directions & does not work
- Very Damaged Anvil -> Wrong directions & does not work

**Grindstone**
- Does not work & wrong directions

**Enchantment Table**
- Does not work

**Lectern**
- Does not work & wrong directions

**Cauldron`**
- Does not work

**Composter**
- Does not work

**Chests**
- Chest -> Does not work
- Trapped Chets -> Does not work
- Ender Chest -> Does not work & wrong directions

**Shulker Box**
- Light Grey Shulker Box-> White Shulker Box
- Gray Shulker Box-> White Shulker Box
- Black Shulker Box-> White Shulker Box
- Brown Shulker Box-> White Shulker Box
- Red Shulker Box-> White Shulker Box
- Orange Shulker Box-> White Shulker Box
- Yellow Shulker Box-> White Shulker Box
- Lime Shulker Box-> White Shulker Box
- Green Shulker Box-> White Shulker Box
- Cyan Shulker Box-> White Shulker Box
- Light Blue Shulker Box-> White Shulker Box
- Blue Shulker Box-> White Shulker Box
- Purple Shulker Box-> White Shulker Box
- Magenta Shulker Box-> White Shulker Box
- Pink Shulker Box-> White Shulker Box

**Armor Stand**
- Does not work

**Juke Box**
- Does not work

**Signs**
- Crimson Sign -> Can not be placed
- Warped Sign -> Can not be placed

**Painting**
- Does not work

**Item Frame**
- Does not work & wrong directions

**Flower Pot**
-> Does not work & no place sounds

**Bucket**
- All buckets does not work

**Skulls**
- All skull become a skellet skull & wrong directions

**Beacon**
- Does not work

**Bell**
- Does not work & wrong directions

**Stonecutter**
- Does not work & wrong directions

**End Protal**
- Wrong directions

**Ender Pearl**
- Does not work and flies through the floor

**End Rod**
- Wrong directions

**End Crystal**
- Can not be placed

**Boats**
All boats does not work

**Rails**
- All rails have a wrong direction

**Minecarts**
- All minecarts does not work

**Redstone**
- Does not work and does not connect

**Buttons**
*All buttons have a wrong direction*

- Spruce Button -> Oak Button 
- Birch Button -> Oak Button 
- Jungle Button  -> Oak Button 
- Acacia Button  -> Oak Button 
- Dark Oak Button -> Oak Button 

**Tripwire**
- Does not work & can not be placed

**Observer**
- Does not work & wrong directions

**Daylight Sensor**
- Does not work

**Dropper**
- Does not work

**Dispenser**
- Does not work

**Pistons**
- Does not work & wrong directions

**TNT**
- Does not work

**Loom**
- Does not work & wrong directions

**Firework**
- Does not work

**Blocks that don't work Page 4**

**Stem**
- Crimson Stem -> Wrong directions
- Warped Stem -> Wrong directions
- Stripped Crimson Stem -> Wrong directions
- Stripped Warped Stem ->Wrong directions
- Crimson Hyphae ->Wrong directions
- Warped Hyphae ->Wrong directions
- Stripped Crimson Hyphae -> Wrong directions
- Stripped WarpedHyphae -> Wrong directions

**Basalt**
- Basalt -> Wrong directions
- Polished Basalt -> Wrong directions

**Soul Soil**
- Wrong directions

**Coarse**
- ->Dirt

**Gravel**
- Gravel does not fall to the ground the block is then despawnt

**Granite**
- Granite -> Stone
- Polished Granite -> Stone

**Diorite**
- Diorite -> Stone
- Polished Diorite -> Stone

**Andesite**
- Andesite-> Stone
- Polished  Andesite -> Stone

**Sand**
- Sand does not fall to the ground the block is then despawnt

**Red Sand**
- Red Sand does not fall to the ground the block is then despawnt

**Log**
- Spruce Log -> Oak Log
- Birch Log -> Oak Log
- Jungle Log ->Oak Log
- Dark Oak Log -> Not available
- Acacia Log -> Not available

**Wood**
- Spruce Wood -> Oak Wood
- Birch Wood -> Oak Wood
- Jungle Wood -> Oak Wood
- Acacia Wood -> Oak Wood
- Dark Oak Wood -> Oak Wood

**Stripped Wood**
- Stripped Oak Wood -> Oak Wood
- Stripped Spruce Wood -> Oak Wood
- Stripped Birch Wood -> Oak Wood
- Stripped Jungle Wood -> Oak Wood
- Stripped Dark Oak Wood -> Oak Wood

**Leaves**
- Spruce Leaves-> Oak Leaves
- Birch Leaves-> Oak Leaves
- Jungle Leaves-> Oak Leaves
- Acacia Leaves-> Oak Leaves
- Dark Oak Leaves-> Oak Leaves

**Sapling**
- Spruce Sapling-> Oak Sapling
- Birch Sapling-> Oak Sapling
- Jungle Sapling-> Oak Sapling
- Acacia Sapling-> Oak Sapling
- Dark Oak Sapling-> Oak Sapling

**Bee Nest**
- Wrong directions

**Carved Pumpkin**
- Wrong directions

**Fern**
- -> Grass

**Large Fern**
- ->Sunflower

**Double Tallgrass**
- -> Sunflower

**Flowers**
- Dandelion -> Poppy
- Poppy -> Dandelion
- Blue Orchid -> Dandelion 
- Allium -> Dandelion 
- Azure Bluet -> Dandelion 
- Red Tulip -> Dandelion 
- Orange Tulip -> Dandelion 
- White Tulip -> Dandelion 
- Pink Tulip -> Dandelion 
- Oyeye Daisy -> Dandelion 
- Cornflower -> Dandelion 
- Lilly of the Valley -> Dandelion 
- Lilac -> Sunflower
- Rose Bush -> Sunflower
- Peony -> Sunflower

**Dead Bush**
- Can not be placed

**Infested Stones**
- Infested Cobbelstone -> Infested Stone
- Infested Stone Brick ->Infested Stone
- Infested Mossy Stone Brick -> Infested Stone
- Infested Cracked Stone Brick -> Infested Stone
- Infested Chiseled Stone Brick -> Infested Stone

**Wet Sponge**
- ->Sponge

**Coral Block**
- Brain Coral Block -> Tube Coral Block
- Bubble Coral Block -> Tube Coral Block
- Fire Coral Block -> Tube Coral Block
- Horn Coral Block -> Tube Coral Block
- Dead Tube Coral Block -> Tube Coral Block
- Dead Brain Coral Block -> Tube Coral Block
- Dead Bubble Coral Block -> Tube Coral Block
- Dead Fire Coral Block -> Tube Coral Block
- Dead Hurn Coral Block -> Tube Coral Block

**Other**
- Damage system does not work
- Hunger system does not work
- Scaffolding function does not work
- Chain can no be placed
- Bone Block has only one direction
- Dark Prismarine -> Prismarine 
- Purpur Pillar -> Purpur Block & I think the block has a bottle direction.
- Purpur Block -> I think the block has a bottle direction.
- When you drop items the item goes through the floor
- Elytra -> When you press space you fly up 
- You can't spawn animals or monsters with your eggs

**Pictures**
![image](https://user-images.githubusercontent.com/19286296/89799054-4b350a80-db2d-11ea-89a1-734a6a8595e3.png)
![image](https://user-images.githubusercontent.com/19286296/89799083-538d4580-db2d-11ea-9a1a-e37205d4b482.png)
![image](https://user-images.githubusercontent.com/19286296/89873971-7ebe7600-dbbb-11ea-9a42-02280b2f5c05.png)

**Wrong Color**
![image](https://user-images.githubusercontent.com/19286296/89874305-f4c2dd00-dbbb-11ea-9eee-c8149b084124.png)

**Comment by ghost** [comment]
Are these still the case? I was planning to write my plugins for this instead of nukkitx. Should I stick to nukkitx for now?

**Comment by LucGamesYT** [comment]
> Are these still the case? I was planning to write my plugins for this instead of nukkitx. Should I stick to nukkitx for now?

Yes I would recommend you to stay with Nukkit for now

**Comment by ghost** [comment]
> > Are these still the case? I was planning to write my plugins for this instead of nukkitx. Should I stick to nukkitx for now?
> 
> Yes I would recommend you to stay with Nukkit for now

Thank you
