### ISSUE TITLE
NukkitX 2.0 Spectator Bug

### ISSUE THREAD

**Issue by XKazzuKX** [CloudburstMC/Server#5]
### Expected Behavior

In spectator mode you can't break blocks.

### Actual Behavior

Going into spectator and breaking blocks and you could walk though once broken them.
https://youtu.be/lSVRuWFm0Eo

### Steps to Reproduce

N/A

### Debug information

* Debug link: https://hastebin.com/zocehabeba
* Timings link (if relevant): None

### Crashdump, Backtrace or Other Files

https://hastebin.com/uvizeloseg.css

**Checklist**:

- [X] I included a `/debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of Nukkit
- [X] I Made sure the bug/error is not caused by a plugin

**Comment by hungerfan55** [comment]
This is a client sided bug btw.

**Comment by Kazzuk** [comment]
#53 Fixes this.
